### ISSUE TITLE
Add submodule MNN to thirdparty for all OSs

### ISSUE THREAD

**Issue by SuperGNUS** [GeniusVentures/thirdparty#13]
https://github.com/FedML-AI/MNN#lightweight

Make sure to add the library to the CommonTargets.Cmake as an external project and that it builds as a library to link against

**Comment by scorpioluck20** [comment]
Hi @SuperGNUS ,
MNN offcial link is: [https://github.com/alibaba/MNN](https://github.com/alibaba/MNN)
Could we consider add submodule from this link?

Brs,
Tan Nguyen

**Comment by scorpioluck20** [comment]
```
TechLeader1000, 1:59 AM
Did not realize it was a fork.  Please use the alibaba one.
@Tan 
```
I will change to use the alibaba MNN

**Comment by scorpioluck20** [comment]
This issue can be close. PR have been merge to develop branch.
