### ISSUE TITLE
MNN build on Linux

### ISSUE THREAD

**Issue by henriqueaklein** [GeniusVentures/thirdparty#39]
When building MNN on Linux the cmake on the original repo has this code:

```
if(CMAKE_SYSTEM_NAME MATCHES "^Linux")
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -D__STRICT_ANSI__")
    if (CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
      # This is to workaround libgcc.a
      set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -stdlib=libc++")
```
This forces the usage of libc++, which makes it so that it doesn't link to everything else, since the project uses libstdc++.

Either we change everything to libc++ (which had some issues) or fork this repo, remove it and investigate why this was inserted in the first place. We should also check any side effects of it

**Comment by EduMenges** [comment]
(Forked MNN)[https://github.com/GeniusVentures/thirdparty/commit/9cebad306ce171036405c109aa993df151fe642e]. I also opened (a pull request on their repo)[https://github.com/alibaba/MNN/pull/2857], hopefully we'll get some anwsers with it.

**Comment by EduMenges** [comment]
The pull requested was accepted without any comments, so I think it was on their part.
