### ISSUE TITLE
Fix OpenSSL shared library build

### ISSUE THREAD

**Issue by henriqueaklein** [GeniusVentures/thirdparty#48]
OpenSSL is generating both static and shared libraries on the same path (at least for Linux).

The folder "/openssl/build/${CMAKE_BUILD_SYSTEM}/lib/" has both sets of libraries and up until now I thought we were using the static one, and that probably is not the case.
On SuperGenius it works, however on GeniusWallet if you use any shared libraries you have to install them in the bundle directory or else it won't find them. So what happens is that with the same cmake configuration of SuperGenius the GeniusWallet errors out:
```
/genius_wallet: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
```
This means that the Linux OpenSSL is using it's shared libraries counterparts, and since on SuperGenius they are in the same folder it hides the error. 
This is my initial assessment. 
 
OpenSSL build needs to be only static libs so we can make sure it doesn't link to anything dynamically.

**Comment by henriqueaklein** [comment]
Already fixed on Linux. Need to check Android and IOS after that

**Comment by EduMenges** [comment]
Checked on other platforms and none of them are building shared libraries for OpenSSL.
