### ISSUE TITLE
Complete CI/CD github actions in thirdparty

### ISSUE THREAD

**Issue by SuperGNUS** [GeniusVentures/thirdparty#5]
to build a cache of libraries for each OS and then a release action to build the thirdparty library as a release to be able to download per os.

The libraries would be published to thirdparty as Linux-thirdParty-v1.zip, etc. for each OS.

The contents of thirdparty would be the cached source code (without .git) and the cached builds of the libraries, boost, grpc lib, grpc executables for host OS, which are now built into the Build/Linux/Release directory.

The github actions file that is mostly done is https://github.com/GeniusVentures/thirdparty/blob/master/.github/workflows/build-targets.yml

And the build-targets-matrix is the last piece that needs to be tested and work, then we can uncomment the other OS's.  Only Linux is being tested first.

**Comment by henriqueaklein** [comment]
Set 4 releases:
- Main Release
- Main Debug
- Develop Release
- Develop Debug

**Comment by henriqueaklein** [comment]
Fix the release to targz only when succeeds. grpc on windows was only 1.8KB (only src and tmp folders) and on Linux debug 1.45GB (with everything including src and tmp)
